# Generated by Django 5.2.3 on 2025-07-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentSubmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
