# Generated by Django 5.1.1 on 2025-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentSubmission', '0002_emailotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
