# Generated by Django 5.2.7 on 2025-10-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentSubmission', '0003_alter_submission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapprovedstudents',
            name='registration_stage',
            field=models.CharField(choices=[('id_entered', 'Id Entered'), ('otp_sent', 'Otp Sent'), ('otp_verified', 'Otp Verified'), ('password_set', 'Password Set'), ('completed', 'Completed')], default='id_entered', max_length=15),
        ),
    ]
