# Generated by Django 5.2.7 on 2025-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentSubmission', '0004_preapprovedstudents_registration_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapprovedstudents',
            name='registration_stage',
            field=models.CharField(blank=True, choices=[('id_entered', 'Id Entered'), ('otp_sent', 'Otp Sent'), ('otp_verified', 'Otp Verified'), ('password_set', 'Password Set'), ('completed', 'Completed')], default=None, max_length=15, null=True),
        ),
    ]
